In [13]:
import sqlite3
import pandas as pd
df = pd.read_csv('../data/processed/superstore_cleaned.csv')
conn = sqlite3.connect('../data/retail.db')
df.to_sql('sales', conn, if_exists='replace', index=False)
print("✅ Data loaded into SQLite")

✅ Data loaded into SQLite

In [15]:
with open('../sql/analysis_queries.sql', 'r') as file:
    sql_content = file.read()

In [16]:
queries = sql_content.split(';')

In [17]:
query1 = queries[0]

df1 = pd.read_sql_query(query1, conn)
df1

   Total_Revenue  Total_Profit  Total_Orders  Avg_Order_Value
0     2297200.86     286397.02          5009           229.86

In [20]:
df1.to_csv('../data/sql_outputs/q1_kpi_summary.csv', index=False)

In [23]:
query2 = queries[1]

df2 = pd.read_sql_query(query2, conn)
df2

                                        Product Name  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier     61599.82
1  Fellowes PB500 Electric Punch Plastic Comb Bin...     27453.38
2  Cisco TelePresence System EX90 Videoconferenci...     22638.48
3       HON 5400 Series Task Chairs for Big and Tall     21870.58
4         GBC DocuBind TL300 Electric Binding System     19823.48
5   GBC Ibimaster 500 Manual ProClick Binding System     19024.50
6               Hewlett Packard LaserJet 3310 Copier     18839.69
7  HP Designjet T520 Inkjet Large Format Printer ...     18374.90
8          GBC DocuBind P400 Electric Binding System     17965.07
9        High Speed Automatic Electric Letter Opener     17030.31

In [24]:
df2.to_csv('../data/sql_outputs/q2_top_products.csv', index=False)

In [25]:
query3 = queries[2]

df3 = pd.read_sql_query(query3, conn)
df3

    Region      Sales     Profit  Profit_Pct
0     West  725457.82  108418.45       14.94
1     East  678781.24   91522.78       13.48
2  Central  501239.89   39706.36        7.92
3    South  391721.91   46749.43       11.93

In [27]:
df3.to_csv('../data/sql_outputs/q3_sales_&_profit_by_region.csv', index=False)

In [28]:
query4 = queries[3]

df4 = pd.read_sql_query(query4, conn)
df4

      Month  Monthly_Sales
0   2014-05      155028.81
1   2014-08      159044.06
2   2015-09      307649.95
3   2015-10      200322.98
4   2016-01       94924.84
5   2016-03      205005.49
6   2016-06      152718.68
7   2016-11      352461.07
8   2016-12      325293.50
9   2017-02       59751.25
10  2017-04      137762.13
11  2017-07      147238.10

In [29]:
df4.to_csv('../data/sql_outputs/q4_monthly_sales_trend.csv', index=False)

In [30]:
query5 = queries[4]

df5 = pd.read_sql_query(query5, conn)
df5

  Sub-Category  Total_Profit
0       Tables     -17725.48
1    Bookcases      -3472.56
2     Supplies      -1189.10

In [36]:
df5.to_csv('../data/sql_outputs/q5_loss_making_sub-categories.csv', index=False)

In [41]:
query6 = queries[5]

df6 = pd.read_sql_query(query6, conn)
df6

       Segment  Customers       Sales  Avg_Sales
0     Consumer        409  1161401.34     223.73
1    Corporate        236   706146.37     233.82
2  Home Office        148   429653.15     240.97

In [42]:
df6.to_csv('../data/sql_outputs/q6_customer_segment_performance.csv', index=False)

In [43]:
query7 = queries[6]

df7 = pd.read_sql_query(query7, conn)
df7

    Year  Quarter  Quarterly_Sales  QoQ_Growth
0   2014        1         74447.80         NaN
1   2014        2         86538.76    12090.96
2   2014        3        143633.21    57094.45
3   2014        4        179627.73    35994.52
4   2015        1         68851.74  -110775.99
5   2015        2         89124.19    20272.45
6   2015        3        130259.58    41135.39
7   2015        4        182297.01    52037.43
8   2016        1         93237.18   -89059.83
9   2016        2        136082.30    42845.12
10  2016        3        143787.36     7705.06
11  2016        4        236098.75    92311.39
12  2017        1        123144.86  -112953.89
13  2017        2        133764.37    10619.51
14  2017        3        196251.96    62487.58
15  2017        4        280054.07    83802.11

In [47]:
df7.to_csv('../data/sql_outputs/q7_quarterly_growth.csv', index=False)

In [46]:
query8 = queries[7]

df8 = pd.read_sql_query(query8, conn)
df8

   Customer Name  Total_Revenue  Orders
0    Sean Miller       25043.05       5
1   Tamara Chand       19052.22       5
2   Raymond Buch       15117.34       6
3   Tom Ashbrook       14595.62       4
4  Adrian Barton       14473.57      10

In [48]:
df8.to_csv('../data/sql_outputs/q8_top_5 _customers_by_revenue.csv', index=False)

In [49]:
query9 = queries[8]

df9 = pd.read_sql_query(query9, conn)
df9

     Discount_Band  Avg_Profit
0      High (>40%)     -106.71
1     Low (â‰¤20%)       26.50
2  Medium (21-40%)      -77.86
3      No Discount       66.90

In [50]:
df9.to_csv('../data/sql_outputs/q9_impact_of_discount_on_rofit.csv', index=False)

In [51]:
query10 = queries[9]

df10 = pd.read_sql_query(query10, conn)
df10

        Ship Mode  Orders  Avg_Ship_Days  Total_Sales
0        Same Day     543            0.0    128363.13
1     First Class    1538            2.2    351428.42
2    Second Class    1945            3.2    459193.57
3  Standard Class    5968            5.0   1358215.74

In [52]:
df10.to_csv('../data/sql_outputs/q10_ship_mode_efficiency.csv', index=False)